# Generated by Django 5.2.6 on 2025-10-15 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Уникальное имя файла', max_length=255)),
                ('original_filename', models.CharField(blank=True, help_text='Оригинальное имя файла', max_length=255, null=True)),
                ('file_path', models.CharField(default='', help_text='Относительный путь к файлу на сервере', max_length=500)),
                ('s3_url', models.URLField(default='', help_text='URL для доступа к файлу', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('lat', models.FloatField(blank=True, help_text='Широта', null=True)),
                ('lon', models.FloatField(blank=True, help_text='Долгота', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_locations', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='image_api.uploadedimage')),
            ],
            options={
                'verbose_name': 'Image Location',
                'verbose_name_plural': 'Image Locations',
                'db_table': 'image_locations',
            },
        ),
    ]
