# Generated by Django 5.2.6 on 2025-10-17 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_uploadedarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelocation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imagelocation',
            name='angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagelocation',
            name='error_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagelocation',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagelocation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagelocation',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DetectedImageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_locations', to='image_api.uploadedimage')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_image_mappings', to='image_api.imagelocation')),
            ],
        ),
    ]
