# Generated by Django 5.2.6 on 2025-10-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0003_imagelocation_address_imagelocation_angle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedimagelocation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
