# Generated by Django 5.2.6 on 2025-10-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0003_imagelocation_address_imagelocation_angle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedarchive',
            name='metadata_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedarchive',
            name='metadata_s3_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
