# Generated by Django 5.2.6 on 2025-10-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0004_detectedimagelocation_address'),
        ('image_api', '0004_uploadedarchive_metadata_filename_and_more'),
    ]

    operations = [
    ]
