services:
  tileserver-gl:
    image: maptiler/tileserver-gl:latest
    container_name: tileserver-gl
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
    command: ["-p","8080","-c","/data/tileserver.json"]