services:
  build_frontend:
    image: node:20-alpine
    working_dir: /src
    volumes:
      - ./:/src
      - /var/www/adress-cv-frontend:/out
    command: >
      sh -c "npm ci &&
             npm run build -- --configuration production --output-path=dist &&
             rm -rf /out/* &&
             cp -r dist/* /out/"